### ISSUE TITLE
Feature request: configure advancement tabs/tab order?

### ISSUE THREAD

**Issue by thecnoNSMB** [42atomys/fabric-advancementinfo-reloaded#21]
Playing with BlazeandCave's Advancements Pack 1.17.2, and the advancement tabs appear in apparently random order. The tabs also spill over into the bottom of the advancement window even though the GUI scale I'm using appears to have plenty of room. The attached screenshot was generated by creating a creative mode test world with the datapack loaded and issuing `/advancement grant [my username] everything`.
![2024-09-29_06 46 24](https://github.com/user-attachments/assets/6b1168d8-4f23-403e-b670-e83f1d95f443)

**Comment by 42atomys** [comment]
Hi @thecnoNSMB, the order are random like in vanilla, an option to sort are a "quick win" to implement so I can add it ✅ 

To customize the number of tab on top and bottom you can change directly in the settings of the mod (by the `ModMenu` mod) or directly inside the configuration file `{{MINECRAFT_INSTALLATION_DIR}}/config/advancementinforeloaded.json5` and change the value
```json5
"aboveWidgetLimit": 14,
"belowWidgetLimit": 14
```
with value you want! This settings are present due to a lot of screen resolution across the globe :)

**Comment by thecnoNSMB** [comment]
Thanks, that does help! I was wondering if it'd be possible for the user to decide directly what order the tabs are in, but I understand if that'd be complicated to implement or error-prone.

**Comment by 42atomys** [comment]
Yes potentials errors are present, imagine ordering 10 tabs for a resource pack and add a new one, the order will be random, need to re-order. Same when remove an ordered tab. 

That not impossible, can be a feature request for the future and see what the community decide, but actually I don't wanna work on this part, my priority are the "search" engine _(and I dont want to work on it ahah)_
