### ISSUE TITLE
feature request: port v0.7.0 feature to 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [42atomys/fabric-advancementinfo-reloaded#39]
### Describe the Request

The new update

### Modloader Type

Neoforge

### Modloader Version

1.21.1

**Comment by 42atomys** [comment]
Hi @VaporeonScripts,

The Mojang API has completely changed between versions 1.21.1 and 1.21.2. Because of this, I need to rewrite some parts of the mod to update it to the latest version of Minecraft.

Backporting the update to 1.21.1 would require me to rewrite the mod with two separate branches. While it's possible, it will take time. If I have extra time before the Winter Drop, I will work on delivering the backported update, but I can't promise I'll have the time right now.

Thank you for your understanding, and stay tuned!

**Comment by VaporeonScripts** [comment]
Oh,if that was the problem,don't worry! I can wait👍

**Comment by 42atomys** [comment]
Thanks for your understanding 💜

**Comment by 42atomys** [comment]
As the Winter Drop already be here, I don't have the time to backport to 1.21.1 and before, I will focus on the next minor bump (1.22) to change how I handle multiple version of minecraft with mod update !

I will close this issue as `Not planned`

Thanks for your understanding 💜

**Comment by VaporeonScripts** [comment]
ig,at this point just warn people that latest 1.21.1 version is broken
