### ISSUE TITLE
feature request: possible port to forge 1.20.1?

### ISSUE THREAD

**Issue by VaporeonScripts** [42atomys/fabric-advancementinfo-reloaded#45]
### Describe the Bug

title

### Steps to Reproduce

a

### Expected Behavior

would be cool tbf

### Screenshots

a

### Modloader Type

Minecraft Forge

### Modloader Version

forge latest

### Mod Version

.

### Log Output

```shell
a
```

### Additional Context

a

**Comment by 42atomys** [comment]
Hi, the first version of the mod are `1.21` because the old AdvancementInfo are available until this version, with the big rework Mojang done in 1.21 and 1.21.3, the backport of the mod are too big for the time I allocate currently with Winter holidays !

I will add a line on README to precise this point to add more clarity to the dicision !

**Comment by VaporeonScripts** [comment]
i know, i respect it, but the old advancementinfo 1.20.1 was only for fabric, anyways, ill stick with better advancements mod ig

**Comment by 42atomys** [comment]
This is why the backport are huge, rewrite all the mod of old version are like re-create the mod integrally for forge and neoforge to let nobody left behind. BetterAdvancement are a good alternative for 1.20.x yes !
